# Development Dockerfile for React application
FROM ubuntu/nginx:1.18-22.04_beta

RUN mkdir /var/www/jobtracker

# Set working directory
WORKDIR /var/www/jobtracker

RUN apt update && apt install -y curl vim
#    nodejs \
#    npm \
RUN curl -fsSL https://deb.nodesource.com/setup_22.x -o /tmp/nodesource_setup.sh && \
    bash /tmp/nodesource_setup.sh && \
    apt update && \
    apt install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy package files
COPY package*.json ./
COPY docker/nginx/portal.jobtracknow.com-dev.conf /etc/nginx/sites-available/portal.jobtracknow.com.conf
COPY docker/nginx/portal.jobtracknow.com-dev-ssl.conf /etc/nginx/sites-available/portal.jobtracknow.com-ssl.conf

# Install all dependencies (including dev dependencies)
RUN npm install && \
    ln -s /etc/nginx/sites-available/portal.jobtracknow.com.conf /etc/nginx/sites-enabled/portal.jobtracknow.com.conf && \
    ln -s /etc/nginx/sites-available/portal.jobtracknow.com-ssl.conf /etc/nginx/sites-enabled/portal.jobtracknow.com-ssl.conf && \
    rm /etc/nginx/sites-enabled/default && \
    service nginx stop && \
    service nginx start

# Copy source code
COPY . .

# Copy entrypoint script
COPY docker-entrypoint.sh /docker-entrypoint.d/
#RUN chmod +x /usr/local/bin/docker-entrypoint.sh
#RUN npm run start

# Expose ports
EXPOSE 80
EXPOSE 443
EXPOSE 3000

CMD ["npm", "run", "start"]
#CMD ["nginx", "-g", "daemon off;"]
# Use entrypoint script
#ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]