# Development Dockerfile for React application
FROM ubuntu/nginx:1.18-22.04_beta

RUN mkdir /var/www/jobtracker

WORKDIR /var/www/jobtracker

RUN apt update && apt install -y curl vim

RUN curl -fsSL https://deb.nodesource.com/setup_22.x -o /tmp/nodesource_setup.sh && \
    bash /tmp/nodesource_setup.sh && \
    apt update && \
    apt install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start"]
